### ISSUE TITLE
Non-existing fonts?

### ISSUE THREAD

**Issue by vtinev** [dimodimow/TableBook#11]
copypasta?
https://github.com/dimodimow/TableBook/blob/5d5e7c5da01c674ecbb5d21422ad44f526431834/table-book-fe/src/globals.scss#L2-L5

**Comment by dimodimow** [comment]
no, i've used it somewhere but currently i can not remember :D

**Comment by vtinev** [comment]
But the fonts don't seem to be coming from anywhere?
