### ISSUE TITLE
Fix your imports

### ISSUE THREAD

**Issue by vtinev** [dimodimow/TableBook#4]
https://github.com/dimodimow/TableBook/blob/5d5e7c5da01c674ecbb5d21422ad44f526431834/table-book-fe/src/components/nav-bar/nav-bar.tsx#L12

```tsx
import { Link } from "react-router-dom";
import "./nav-bar.scss";
import logoPng from "/images/table-book-logo.png"; // <--

const NavBar = () => {
  return (
    <nav className="nav-bar">
      <div className="nav-bar-items">
        <Link to="/sofia">
          <img
            className="logo"
            height={75}
            src={logoPng} // <--
            alt="Logo"
          />
        </Link>
      </div>
    </nav>
  );
};

export default NavBar;
```

Same story in SCSS files.

**Comment by dimodimow** [comment]
done, close after check

**Comment by vtinev** [comment]
https://github.com/dimodimow/TableBook/blob/5d5e7c5da01c674ecbb5d21422ad44f526431834/table-book-fe/src/components/restaurants-overview/overview.scss#L10

Check everywhere.
