### ISSUE TITLE
Google maps is broken on initial load

### ISSUE THREAD

**Issue by vtinev** [dimodimow/TableBook#5]
Broken on load, appears above the content. Fixes itself on refresh.

![image](https://github.com/dimodimow/TableBook/assets/54780475/6f4c9473-2995-43f1-b661-d0355b5e3ff9)

**Comment by dimodimow** [comment]
@vtinev the reason why it is broken is that, you don't have the token key for the google api and that's why it is broken i will include the key in the next stages when I deploy the application to the cloud, and it should be fixed

**Comment by dimodimow** [comment]
so i think we can close this issue?
