### ISSUE TITLE
[SCSS] Reset is needlesly specific

### ISSUE THREAD

**Issue by vtinev** [dimodimow/TableBook#7]
https://github.com/dimodimow/TableBook/blob/5d5e7c5da01c674ecbb5d21422ad44f526431834/table-book-fe/src/resets.scss#L1-L88

Just select everything.
```scss
*, 
*::before, 
*::after {
 // styles
}
```

---

Font reset makes no sense.
https://github.com/dimodimow/TableBook/blob/5d5e7c5da01c674ecbb5d21422ad44f526431834/table-book-fe/src/resets.scss#L85-L86
Just use this one.
```scss
 font-family: inherit;
```
Additionally, `font` is a shorthand property that [includes everything](https://www.w3schools.com/cssref/pr_font_font.php), so setting another font property besides this one is redundant. Like setting `margin` and then `margin-top`.

Never reset the font-size. You have elements that NEED to be larger than others - for example headings.

---

What?
https://github.com/dimodimow/TableBook/blob/5d5e7c5da01c674ecbb5d21422ad44f526431834/table-book-fe/src/resets.scss#L116-L120

---

These are already block.

https://github.com/dimodimow/TableBook/blob/5d5e7c5da01c674ecbb5d21422ad44f526431834/table-book-fe/src/resets.scss#L90-L102

---

**Comment by dimodimow** [comment]
so i can just add this `*, 
*::before, 
*::after {
 // styles
}`

instead of everything else

**Comment by dimodimow** [comment]
done, close after check
