### ISSUE TITLE
UI/UX: Restaurant info & photos

### ISSUE THREAD

**Issue by vtinev** [dimodimow/TableBook#8]
![image](https://github.com/dimodimow/TableBook/assets/54780475/5369f37c-3db1-46d3-b921-09d8973ea0cc)

- The logo and location should be links.
- Rounded edges everywhere.
- Location link has a hover
- Calendar dates are larger 
- Font: `PT Sans`

**Comment by dimodimow** [comment]
when i click the logo and location it should be redirected to where ? @vtinev

**Comment by dimodimow** [comment]
everything is done, only i need answer about the links and the redirection @vtinev

**Comment by vtinev** [comment]
- Logo should point to Restaurant's website
- Locaton should point to Google maps (use target="_blank")
